OPSEXP-2519 Bump supported matrix for acs 23.2 release
Alfresco/alfresco-updatecli pull request #27
Opened 2024-02-27 15:15 UTC by pmacius

!Ref OPSEXP-2519

2024-03-01 11:47 UTC, pmacius commented
We are still waiting for some of the releases but we can save some time if you take a quick look at this and then merge it when releases will be on the shelf 😃

2024-03-01 13:12 UTC, alxgomz requested changes

2024-03-01 13:12 UTC, alxgomz commented on deployments/values/supported-matrix.yaml
>        version: &tengine_ga_version "~5.0.0"
Needs a bump to 5.1.x (tengine is what is refered to as T-Core in PRODDEL)

2024-03-01 13:12 UTC, alxgomz commented on deployments/values/supported-matrix.yaml
> +      version: "5.0"
We're not releasing a GA during this train so we have to stick to 4.0 for now

2024-03-01 13:39 UTC, gionn commented on deployments/values/supported-matrix.yaml
> +      version: ">=4.1.0-0"
not really necessary, we can even put `>=0.0.0-0` here if you think is more clear or keep as it is

2024-03-01 13:39 UTC, gionn commented on deployments/values/supported-matrix.yaml
> +      version: "23.2"
you can reuse the *acs_ga_version anchor, it's probably a miss when we introduced it

2024-03-01 16:49 UTC, alxgomz approved these changes

2024-03-04 08:05 UTC, gionn approved these changes

2024-03-04 13:45 UTC, merged